# Generated by Django 3.2.8 on 2022-02-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellidos', models.TextField()),
                ('anno', models.IntegerField()),
                ('grupo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(verbose_name='Año')),
                ('investigacion', models.TextField(verbose_name='Investigacion')),
                ('cultura', models.TextField(verbose_name='Cultura')),
                ('docencia', models.TextField(verbose_name='Docencia')),
                ('extension', models.TextField(verbose_name='Extension')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGI_APP.estudiante')),
            ],
        ),
    ]
