# Generated by Django 3.2.8 on 2022-02-17 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGI_APP', '0004_auto_20220216_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='caracterizacion',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='caract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SGI_APP.caracterizacion'),
        ),
    ]
