# Generated by Django 3.2.8 on 2022-02-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGI_APP', '0005_auto_20220216_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='caract',
            new_name='caracterizacion',
        ),
    ]
