# Generated by Django 3.2.8 on 2022-02-17 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SGI_APP', '0006_rename_caract_evaluacion_caracterizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracterizacion',
            options={'verbose_name': 'Caracterizacion', 'verbose_name_plural': 'Caracterizaciones'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name': 'Evaluacion', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='caracterizacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SGI_APP.caracterizacion'),
        ),
    ]
