# Generated by Django 3.2.8 on 2022-02-17 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SGI_APP', '0007_auto_20220217_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='anno',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
