# Generated by Django 3.2.8 on 2022-02-17 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGI_APP', '0008_auto_20220217_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('caracterizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SGI_APP.caracterizacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGI_APP.estudiante')),
            ],
        ),
    ]
