# Generated by Django 3.2.8 on 2022-02-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI_APP', '0010_auto_20220217_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacion',
            name='anno',
            field=models.PositiveIntegerField(null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='anno',
            field=models.PositiveIntegerField(null=True, verbose_name='Año'),
        ),
        migrations.DeleteModel(
            name='AnnoAcademico',
        ),
    ]
