# Generated by Django 3.2.8 on 2022-02-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI_APP', '0011_auto_20220217_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacion',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='modificado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
