# Generated by Django 3.2.8 on 2022-02-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI_APP', '0012_auto_20220217_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterizacion',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
