# Generated by Django 3.2.9 on 2022-02-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGI_APP', '0013_alter_caracterizacion_modificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SGI_APP.profesor')),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGI_APP.grupo'),
        ),
    ]
